### ISSUE TITLE
Failing to Build WASM. Expeceted Task, found FakeTask.

### ISSUE THREAD

**Issue by AlexandreColauto** [foxzool/bevy_http_client#5]
Hello. I'm building a game using Bevy and I need to make an HTTP request to my server. 
The project compiles and works fine when I compile it into machine code. But when I try to compile to wasm I get the attached error: 
![Screenshot from 2024-02-25 16-21-05](https://github.com/foxzool/bevy_http_client/assets/43041764/f86a2d7b-8c26-49f7-b523-77c03d7254a5)

I tried to disable the default features and add them one by one. I even upgraded my Bevy from 0.11 which was using version 0.1 of the library to Bevy 0.12 to use the newest version of the library (0.3). But I still getting the same error. I tried every documentation that I found and nothing seems to work. I end up using straight ehttp, which works normally. 

My Cargo.toml file: 
```
[package]
name = "w_map"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
opt-level = 'z'
lto = "thin"

[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"


[dependencies]
# Dependencies for WASM only.
bevy = { version = "0.12.1",default-features = false, features = ["bevy_asset", "bevy_winit",  "webgl2","multi-threaded"] }
bevy_ecs_tilemap = "0.12.0"
webbrowser = "0.8.12"
csv = "1.3.0"
bevy_http_client = "0.3.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
```

Cargo 1.76.0

**Comment by foxzool** [comment]
just release 0.5.1 for fix wasm error.

**Comment by foxzool** [comment]
add an online wasm example 
https://foxzool.github.io/bevy_http_client/
