### ISSUE TITLE
typed example

### ISSUE THREAD

**Issue by ajerni** [foxzool/bevy_http_client#7]
is the typed example up to date? I do not find the `register_request_type` method.

**Comment by foxzool** [comment]
any log?  Just test a new empty project on windows, typed example works

**Comment by ajerni** [comment]
ok - thanks, just wanted to know, so I start testing it. Thanks. One more question: Can I use this crate also to send PATCH requests containing raw JSON in the body?

**Comment by ajerni** [comment]
I leave this here for reference if somebody looks for an example of how to add a JSON raw payload:
```
fn send_request_update(mut ev_request: EventWriter<HttpRequest>) {
    let payload = serde_json::json!({"name":"Test","test":"Bevy Data"});

    let request = HttpClient::new()
        .patch("https://server.com/update/xyz")
        .json(&payload)
        .build();

    ev_request.send(request);
}
```
