### ISSUE TITLE
Allow to extract inner type 

### ISSUE THREAD

**Issue by occuros** [foxzool/bevy_http_client#8]
Currently the inner type is private:

```rust
#[derive(Debug, Deref, Event)]
pub struct TypedResponse<T>
where
    T: for<'a> Deserialize<'a>,
{
    #[deref]
    inner: T,
}
```

And I haven't found a way to extract the inner type directly from the TypedResponse.

**Comment by foxzool** [comment]
TypeResonese  has deref trait,       what context for need direct access for inner ?

**Comment by occuros** [comment]
Indeed that resolves it.

```rust

let inner =   response.deref();
```
